export const SET_CWL_OBJECT = 'SET_CWL_OBJECT';
export const CHANGE_APP_PACKAGE_NAME = 'CHANGE_APP_PACKAGE_NAME';
export const CHANGE_APP_PACKAGE_VERSION = 'CHANGE_APP_PACKAGE_VERSION';
export const SET_MODE = 'SET_MODE';
export const RESET_EDITOR = 'RESET_EDITOR';

// METADATA
export const CHANGE_NS_PREFIX = 'CHANGE_NS_PREFIX';
export const EDIT_NAMESPACE = 'EDIT_NAMESPACE';
export const ADD_NAMESPACE = 'ADD_NAMESPACE';
export const REMOVE_NAMESPACE = 'REMOVE_NAMESPACE';

// COMMAND LINE TOOL
export const ADD_COMMAND_LINE_TOOL = 'ADD_COMMAND_LINE_TOOL';
export const REMOVE_COMMAND_LINE_TOOL = 'REMOVE_COMMAND_LINE_TOOL';
export const EDIT_COMMAND_LINE_TOOL = 'EDIT_COMMAND_LINE_TOOL';
export const REMOVE_COMMAND_LINE_TOOL_ELEMENT = 'REMOVE_COMMAND_LINE_TOOL_ELEMENT';
export const ADD_COMMAND_LINE_TOOL_ELEMENT = 'ADD_COMMAND_LINE_TOOL_ELEMENT';
export const EDIT_CMD_ID = 'EDIT_CMD_ID';

// WORKFLOW
export const EDIT_WORKFLOW = 'EDIT_WORKFLOW';
export const REMOVE_WORKFLOW_ELEMENT = 'REMOVE_WORKFLOW_ELEMENT';
export const ADD_WORKFLOW_ELEMENT = 'ADD_WORKFLOW_ELEMENT';
